-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 12:45:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  `country_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`state` (
  `state_id` INT NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `street_address` VARCHAR(45) NULL DEFAULT NULL,
  `apt_num` INT NULL DEFAULT NULL,
  `zip_code` INT NULL DEFAULT NULL,
  `cityID` INT NULL DEFAULT NULL,
  `countryID` INT NULL DEFAULT NULL,
  `StateID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `a_person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `a_city_id_idx` (`cityID` ASC) VISIBLE,
  INDEX `a_state_id_idx` (`StateID` ASC) VISIBLE,
  INDEX `a_country_id_idx` (`countryID` ASC) VISIBLE,
  CONSTRAINT `a_city_id`
    FOREIGN KEY (`cityID`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_country_id`
    FOREIGN KEY (`countryID`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_state_id`
    FOREIGN KEY (`StateID`)
    REFERENCES `mydb`.`state` (`state_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`social_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_platform` (
  `social_platform_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`social_platform_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`social_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_account` (
  `social_account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `person_id` INT NULL DEFAULT NULL,
  `platform_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_account_id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `platform_id_idx` (`platform_id` ASC) VISIBLE,
  CONSTRAINT `sa_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sa_platform_id`
    FOREIGN KEY (`platform_id`)
    REFERENCES `mydb`.`social_platform` (`social_platform_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`device_make`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`device_make` (
  `device_make_id` INT NOT NULL AUTO_INCREMENT,
  `make_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`device_make_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`device_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`device_model` (
  `device_model_id` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NULL DEFAULT NULL,
  `make_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`device_model_id`),
  INDEX `dm_make_id_idx` (`make_id` ASC) VISIBLE,
  CONSTRAINT `dm_make_id`
    FOREIGN KEY (`make_id`)
    REFERENCES `mydb`.`device_make` (`device_make_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `model_id` INT NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`device_id`),
  INDEX `dev_account_id_idx` (`account_id` ASC) VISIBLE,
  INDEX `dev_model_id_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `dev_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dev_model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `mydb`.`device_model` (`device_model_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email` (
  `email_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `email_address` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`email_id`),
  INDEX `e_person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `e_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`login_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login_event` (
  `login_event_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `device_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`login_event_id`),
  INDEX `li_device_id_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `li_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`device` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`logout_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`logout_event` (
  `logout_event_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `device_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`logout_event_id`),
  INDEX `lo_device_id_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `lo_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `mydb`.`device` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `phone_id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NULL DEFAULT NULL,
  `country_code` INT NULL DEFAULT NULL,
  `phone_num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`phone_id`),
  INDEX `p_person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `p_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `purchase_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `seller_acc_id` INT NULL DEFAULT NULL,
  `buyer_acc_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `pur_seller_id_idx` (`seller_acc_id` ASC) VISIBLE,
  INDEX `pur_buyer_id_idx` (`buyer_acc_id` ASC) VISIBLE,
  CONSTRAINT `pur_buyer_id`
    FOREIGN KEY (`buyer_acc_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pur_seller_id`
    FOREIGN KEY (`seller_acc_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_products` (
  `purchase_products_id` INT NOT NULL AUTO_INCREMENT,
  `qty` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `purchase_id` INT NULL,
  PRIMARY KEY (`purchase_products_id`),
  INDEX `pp_product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `pp_purchase_id_idx` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `pp_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pp_purchase_id`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `mydb`.`purchase` (`purchase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`social_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_post` (
  `social_post_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_post_id`),
  INDEX `sp_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `sp_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`social_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_comment` (
  `social_comment_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_comment_id`),
  INDEX `sc_post_id_idx` (`post_id` ASC) VISIBLE,
  INDEX `sc_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `sc_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sc_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`social_post` (`social_post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`social_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`social_like` (
  `social_like_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `account_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`social_like_id`),
  INDEX `sl_post_id_idx` (`post_id` ASC) VISIBLE,
  INDEX `sl_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `sl_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`social_account` (`social_account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `sl_post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`social_post` (`social_post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
